"""Manual accounting-year management, extending the existing local dashboard."""

STYLE = r'''
.year-hero{display:flex;justify-content:space-between;align-items:center;background:#173f46;color:#fff;border-radius:16px;padding:30px 34px;margin-bottom:18px;gap:24px}
.year-hero h2{font-family:"Songti SC","SimSun",serif;font-size:28px;letter-spacing:1px;margin:8px 0 12px}.year-hero p{color:#c9dde0;margin:0;line-height:1.7}.year-eyebrow{font-size:12px;letter-spacing:2px;color:#d3b87b}.year-state{border:1px solid #789ba0;padding:12px 18px;border-radius:6px;white-space:nowrap}
.year-process{display:grid;grid-template-columns:repeat(4,1fr);border-bottom:1px solid #d4dcdf;padding-bottom:20px;gap:16px;margin:22px 0}.year-process span{color:#7a8387;font-size:13px}.year-process strong{display:block;color:#244a51;font-size:15px;margin-top:5px}.year-process b{font-family:Georgia,serif;font-size:24px;color:#9f8650;margin-right:8px}
.year-grid{display:grid;grid-template-columns:1.05fr 1fr;gap:20px}.year-fields{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:18px 0}.year-fields label{display:block;font-size:14px;color:#4b6065}.year-fields input{margin-top:8px;width:100%;box-sizing:border-box}.year-note{font-size:13px;color:#65777b;line-height:1.8}.year-policy{background:#f4f6f3;border-left:3px solid #ac925c;padding:14px 18px;margin:16px 0}.year-kv{display:grid;grid-template-columns:120px 1fr;line-height:2.2;margin:12px 0}.year-kv dt{color:#6a777d}.year-kv dd{margin:0;font-weight:600;overflow-wrap:anywhere}.year-history{margin-top:20px}.year-history td{padding:14px 12px}.year-actions{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.year-actions button{min-height:42px}.year-empty{padding:30px 10px;text-align:center;color:#768387}.year-detail{border-top:1px solid #d7dfe1;margin-top:20px;padding-top:20px}.year-detail h3{font-size:16px}.year-message{min-height:24px;padding:10px 0;line-height:1.6}.year-summary{background:#f4f7f8;padding:16px;margin:12px 0;line-height:1.8}.year-history table{width:100%}
@media(max-width:900px){.year-grid{grid-template-columns:1fr}.year-hero{padding:24px}.year-process{grid-template-columns:1fr 1fr}}
@media(max-width:600px){.year-hero{display:block}.year-state{display:inline-block;margin-top:18px}.year-fields{grid-template-columns:1fr}.year-process strong{font-size:13px}}
'''

HTML = r'''
<main id="archiveView" class="hidden">
 <section class="year-hero"><div><span class="year-eyebrow">YEAR END / 统计年度管理</span><h2>年度，由你决定何时结束。</h2><p>手动关账，保存本年度汇总。准备好之后，再开启新的统计年度。</p></div><span id="yearState" class="year-state">正在读取…</span></section>
 <div class="year-process" aria-label="年度操作流程"><div><b>01</b><span>持续累计</span><strong>本年度统计中</strong></div><div><b>02</b><span>自主选择日期</span><strong>结束并归档</strong></div><div><b>03</b><span>暂停期不补入</span><strong>等待下次开启</strong></div><div><b>04</b><span>新周期重新累计</span><strong>开启下一年度</strong></div></div>
 <div id="yearMessage" class="year-message" role="status" aria-live="polite"></div>
 <div class="year-grid"><section class="card"><div class="section-title"><h2>当前年度</h2><button id="yearRefresh" class="secondary">刷新状态</button></div><dl id="yearCurrent" class="year-kv"></dl><div id="yearPolicy" class="year-policy year-note"></div><div id="yearGroups" class="year-note"></div></section>
 <section class="card"><h2 id="yearActionTitle">年度操作</h2>
 <form id="yearOpenForm"><div class="year-fields"><label for="yearName">统计年度名称<input id="yearName" maxlength="60" placeholder="例如：2026经营年度" required></label><label for="yearStart">开始日期<input id="yearStart" type="date" required></label></div><p id="yearOpenNote" class="year-note"></p><button id="yearOpen" class="primary" type="submit">启用手动年度</button></form>
 <form id="yearCloseForm" class="hidden"><div class="year-fields"><label for="yearEnd">统计截止日期（含当天）<input id="yearEnd" type="date" required></label></div><p class="year-note">保存关账时已入库、且生效日期在本年度范围内的数据。之后进入暂停；不删除历史报价。</p><button id="yearPreview" class="danger" type="submit">预览并结束本年度</button></form>
 <div id="yearWorking" class="hidden"><p id="yearWorkNote" class="year-note"></p><button id="yearRetry" class="secondary hidden">重试归档</button></div>
 </section></div>
 <section class="card year-history"><h2>年度归档记录</h2><p class="year-note">固定快照包含报价明细及大类、小类的日 / 周 / 月 / 年汇总。归档完成后，后续消息、配置调整或原始数据删除都不会自动改写该快照。</p><div id="yearHistory" class="table-wrap"></div><div id="yearDetails"></div></section>
 <p class="year-note">启用手动模式后，“数据与报表”的日均统计只显示当前年度。新报表位于“手动年度统计 / 当前”；以前的春节自动报表仍保留，但不再作为当前年度结果更新。此页面统一控制已配置的QQ群，手动文本统计模式不受影响。</p>
</main>
<dialog id="yearDialog" aria-labelledby="yearDialogTitle"><div class="dialog-head"><h3 id="yearDialogTitle">确认年度操作</h3></div><div class="dialog-body"><div id="yearConfirmBody" class="year-summary"></div><p id="yearConfirmError" class="bad" role="alert"></p></div><div class="dialog-actions"><button id="yearCancel" class="secondary">取消</button><button id="yearConfirm" class="primary">确认操作</button></div></dialog>
'''

SCRIPT = r'''
<script>
const YM={state:null,action:'',body:null,busy:false,seq:0};
const ys={active:'统计中',closing:'正在生成归档',closed:'已归档 · 等待开启',error:'归档失败 · 可重试'};
function yearMessage(text,bad=false){dq('#yearMessage').textContent=text;dq('#yearMessage').classList.toggle('bad',bad)}
async function yearLoad(){const seq=++YM.seq;try{const s=await dataApi('archive-status');if(seq!==YM.seq)return;const previous=YM.state?.current?.state;YM.state=s;yearRender(s);if(previous==='closing'&&s.current?.state==='closed')yearMessage('本年度归档已完成，可查看汇总或下载Excel。');if(previous==='closing'&&s.current?.state==='error')yearMessage(s.current.error,true)}catch(e){yearMessage(e.message,true)}}
function yearRender(s){const c=s.current,first=!c;dq('#yearState').textContent=first?'尚未启用手动年度':ys[c.state];dq('#yearCurrent').innerHTML=first?'<dt>当前模式</dt><dd>春节自动统计（现有模式）</dd><dt>手动年度</dt><dd>尚未设置</dd>':`<dt>年度名称</dt><dd>${dh(c.name)}</dd><dt>开始日期</dt><dd>${dh(c.start_day)}</dd><dt>截止日期</dt><dd>${dh(c.end_day||'由你决定')}</dd><dt>年度状态</dt><dd>${dh(ys[c.state])}</dd>`;dq('#yearPolicy').textContent=first?'首次启用不会删除旧数据。请选择本年度起始日，已有范围内记录将纳入统计。':'暂停期间不计入任何年度；以后开启下一年度时，开启前已入库的记录不会自动补入。原始记录可在数据页面查询。';dq('#yearGroups').textContent=`统一应用到 ${s.groups.length} 个已配置QQ群：`+s.groups.map(g=>g.name).join('、');const canOpen=first||c.state==='closed';dq('#yearOpenForm').classList.toggle('hidden',!canOpen);dq('#yearCloseForm').classList.toggle('hidden',!c||c.state!=='active');dq('#yearWorking').classList.toggle('hidden',!c||!['closing','error'].includes(c.state));dq('#yearRetry').classList.toggle('hidden',!c||c.state!=='error');dq('#yearActionTitle').textContent=first?'开始手动管理':c.state==='active'?'结束本年度':c.state==='closed'?'开启下一年度':'归档任务';if(canOpen){if(document.activeElement!==dq('#yearName')&&!dq('#yearName').dataset.edited)dq('#yearName').value=first?s.today.slice(0,4)+'统计年度':'第'+(c.id+1)+'统计年度';if(document.activeElement!==dq('#yearStart')&&!dq('#yearStart').dataset.edited)dq('#yearStart').value=s.suggested_start;dq('#yearStart').max=s.today;dq('#yearStart').min=first?'':s.suggested_start;dq('#yearOpen').disabled=YM.busy||!s.groups.length||s.suggested_start>s.today;dq('#yearOpen').textContent=first?'启用手动年度':'开启下一年度';dq('#yearOpenNote').textContent=first?'可选择过去的起始日纳入现有数据。启用后不会再按春节自动切换年度。':s.suggested_start>s.today?'统计按天划分，本年度截止日已包含今天；最早明天可开启下一年度。':'新年度从今天开始，暂停期间的数据不补入。';}if(c&&c.state==='active'){dq('#yearEnd').min=c.start_day;dq('#yearEnd').max=s.today;if(!dq('#yearEnd').dataset.edited)dq('#yearEnd').value=s.today;}dq('#yearWorkNote').textContent=c?.state==='error'?c.error:'关账快照已保存，正在生成所有群的Excel和CSV。此时不会继续累计，完成后再开启新年度。';dq('#yearHistory').innerHTML=s.cycles.length?'<table><thead><tr><th>年度</th><th>统计日期</th><th>状态</th><th>操作</th></tr></thead><tbody>'+s.cycles.map(c=>`<tr><td>${dh(c.name)}</td><td>${dh(c.start_day)} → ${dh(c.end_day||'尚未截止')}</td><td>${dh(ys[c.state])}</td><td>${c.state==='closed'?`<button class="secondary year-detail-button" data-cycle="${c.id}">查看汇总</button>`:'—'}</td></tr>`).join('')+'</tbody></table>':'<p class="year-empty">还没有手动归档记录。完成第一次关账后，这里会保存本年度汇总。</p>';document.querySelectorAll('.year-detail-button').forEach(b=>b.onclick=()=>yearDetails(b.dataset.cycle));}
async function yearDetails(id){try{const x=await dataApi('archive-details?'+new URLSearchParams({cycle_id:id}));dq('#yearDetails').innerHTML=`<div class="year-detail"><h3>${dh(x.name)} · 关账快照</h3>`+x.groups.map(g=>`<section><h3>${dh(g.name)} · ${g.count} 条报价</h3>${g.configured?`<a href="/api/data/file?${dh(new URLSearchParams({group_id:g.id,path:g.path,download:'1'}).toString())}">下载年度Excel</a>`:'<p class="year-note">该群已移出配置，原归档仍保存在本机群目录。</p>'}<div class="table-wrap"><table><thead><tr><th>线路</th><th>货物</th><th>年度均价</th><th>数据月份</th><th>报价数</th></tr></thead><tbody>${g.annual.map(r=>`<tr><td>${dh(r.始发地)} → ${dh(r.目的城市)}</td><td>${dh(r.货物)}</td><td>${dn(r.平均运价)}</td><td>${r.数据月份数}</td><td>${r.报价数量}</td></tr>`).join('')||'<tr><td colspan="5">没有参与均价的报价（可能为空年度或均为整车价）。</td></tr>'}</tbody></table></div></section>`).join('')+'</div>'}catch(e){yearMessage(e.message,true)}}
function yearDialog(action,body,html){YM.action=action;YM.body=body;dq('#yearConfirmBody').innerHTML=html;dq('#yearConfirmError').textContent='';dq('#yearConfirm').disabled=false;dq('#yearDialog').showModal()}
dq('#yearOpenForm').onsubmit=e=>{e.preventDefault();if(!YM.state||YM.busy)return;const name=dq('#yearName').value.trim(),start=dq('#yearStart').value;yearDialog('archive-open',{version:YM.state.version,name,start_day:start},`<strong>${dh(name)}</strong><br>开始日期：${dh(start)}<br>应用到全部已配置QQ群。${YM.state.current?'开启前已入库数据不补入。':'首次启用会纳入起始日之后的已有报价。'}旧数据和旧报表不会删除。`)};
dq('#yearCloseForm').onsubmit=async e=>{e.preventDefault();if(YM.busy)return;try{const x=await dataApi('archive-preview',{end_day:dq('#yearEnd').value});yearDialog('archive-close',{version:x.version,end_day:x.end_day},`<strong>结束 ${dh(x.name)}</strong><br>${dh(x.start_day)} 至 ${dh(x.end_day)}（含截止日）<br>${x.groups.map(g=>dh(g.name)+'：'+g.count+' 条').join('<br>')}<p>${dh(x.message)}</p><p>关账后不能直接撤销；快照不会随后续数据删除而自动更新。</p>`)}catch(e){yearMessage(e.message,true)}};
dq('#yearRetry').onclick=()=>yearDialog('archive-retry',{version:YM.state.version},'使用原关账快照重新生成报表，不重新采集、不重新取数。');
dq('#yearConfirm').onclick=async()=>{if(YM.busy)return;YM.busy=true;dq('#yearConfirm').disabled=true;dq('#yearCancel').disabled=true;try{const x=await dataApi(YM.action,{...YM.body,confirm:true});dq('#yearDialog').close();for(const id of ['yearName','yearStart','yearEnd'])delete dq('#'+id).dataset.edited;await yearLoad();yearMessage(['archive-close','archive-retry'].includes(YM.action)&&YM.state?.current?.state==='closed'?'本年度归档已完成，可查看汇总或下载Excel。':x.message)}catch(e){dq('#yearConfirmError').textContent=e.message}finally{YM.busy=false;dq('#yearConfirm').disabled=false;dq('#yearCancel').disabled=false;if(YM.state)yearRender(YM.state)}};
dq('#yearCancel').onclick=()=>dq('#yearDialog').close();dq('#yearDialog').addEventListener('cancel',e=>{if(YM.busy)e.preventDefault()});
for(const id of ['yearName','yearStart','yearEnd'])dq('#'+id).oninput=()=>dq('#'+id).dataset.edited='1';
dq('#yearRefresh').onclick=yearLoad;dq('[data-view="archive"]').addEventListener('click',yearLoad);
setInterval(()=>{if(!dq('#archiveView').classList.contains('hidden')&&!dq('#yearDialog').open&&!YM.busy)yearLoad()},3000);
if(new URLSearchParams(location.search).get('view')==='archive')dq('[data-view="archive"]').click();
</script>
'''


def extend_archive_dashboard(html: str) -> str:
    html=html.replace('</style>',STYLE+'</style>',1)
    html=html.replace('<button class="tab" data-view="config">','<button class="tab" data-view="archive">年度归档</button><button class="tab" data-view="config">',1)
    html=html.replace('<main id="configView"',HTML+'<main id="configView"',1)
    html=html.replace("const data=b.dataset.view==='data';", "const archive=b.dataset.view==='archive';$('#archiveView').classList.toggle('hidden',!archive);const data=b.dataset.view==='data';",1)
    html=html.replace("classList.toggle('hidden',config||data)","classList.toggle('hidden',config||data||archive)",1)
    html=html.replace("async function refreshAll(){if(!$('#dataView')", "async function refreshAll(){if(!$('#archiveView').classList.contains('hidden'))return;if(!$('#dataView')",1)
    html=html.replace("function dataReportState(s){", "function dataReportState(s){if(s?.manual)return '手动年度报表请查看“手动年度统计/当前”和“手动年度归档”；其他路径为保留的旧模式报表。'+(s.pending?' 当前报表正在更新。':'');",1)
    html=html.replace("${r.eligible===false?", "${r.year_note?'<small class=\"muted\"> '+dh(r.year_note)+'</small>':''}${r.eligible===false?",1)
    return html.replace('</body>',SCRIPT+'</body>',1)
